// log in as Mateusz
POST https://localhost:7256/auth/login
Content-Type: application/json

{ "Username" : "trmo", "Password" : "onetwo3FOUR" }


###

GET https://localhost:7256/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI1NjU5ZTkyMi00YmVjLTQ2ZjQtODk0Yi05ZjA4ZjdjMzA5YjgiLCJpYXQiOiIxMS81LzIwMjIgOTo1NDo0OCBQTSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ0cm1vIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVGVhY2hlciIsIkRpc3BsYXlOYW1lIjoiVHJvZWxzIE1vcnRlbnNlbiIsIkFnZSI6IjM2IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjQiLCJleHAiOjE2Njc2ODg4ODgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ._xOucRreSUC2gxYK7sQLf0dHZluz_EMun2ed7D3AZVwfpeQ3Imj-k4VaqvMbzVwP41Zvq4LPCqYORyqpa71piA


